app:
  test: This is BOT ApplicationConfig!

  bot:
    apiKey: ${BOT_API_KEY}

  queue-name: queue

  exchange-name: exchange

  use-queue: true

server:
  port: 8081


springdoc:
  swagger-ui:
    path: /swagger-ui
