/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.entity.jooq.tables.records;


import jakarta.validation.constraints.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import ru.tinkoff.edu.java.scrapper.entity.jooq.tables.TgChat;

import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.17.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TgChatRecord extends UpdatableRecordImpl<TgChatRecord> implements Record2<Long, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TG_CHAT.ID</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>TG_CHAT.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>TG_CHAT.CREATED_AT</code>.
     */
    public void setCreatedAt(@NotNull OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>TG_CHAT.CREATED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, OffsetDateTime> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, OffsetDateTime> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return TgChat.TG_CHAT.ID;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field2() {
        return TgChat.TG_CHAT.CREATED_AT;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public OffsetDateTime component2() {
        return getCreatedAt();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public OffsetDateTime value2() {
        return getCreatedAt();
    }

    @Override
    @NotNull
    public TgChatRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public TgChatRecord value2(@NotNull OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public TgChatRecord values(@NotNull Long value1, @NotNull OffsetDateTime value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TgChatRecord
     */
    public TgChatRecord() {
        super(TgChat.TG_CHAT);
    }

    /**
     * Create a detached, initialised TgChatRecord
     */
    @ConstructorProperties({"id", "createdAt"})
    public TgChatRecord(@NotNull Long id, @NotNull OffsetDateTime createdAt) {
        super(TgChat.TG_CHAT);

        setId(id);
        setCreatedAt(createdAt);
    }

    /**
     * Create a detached, initialised TgChatRecord
     */
    public TgChatRecord(ru.tinkoff.edu.java.scrapper.entity.jooq.tables.pojos.TgChat value) {
        super(TgChat.TG_CHAT);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
        }
    }
}
