name: Scrapper CI

on:
  push:
    paths:
      - "project/scrapper/**"
      - "project/link-parser/**"
      - "project/scrapper.Dockerfile"
      - "project/pom.xml"
      - ".github/workflows/scrapper.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: cd project && mvn clean && mvn package -pl scrapper -am

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: cd project && docker build --file scrapper.Dockerfile -t ghcr.io/melmelnikoff/scrapper:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/melmelnikoff/scrapper:latest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run check style
        run: cd project && mvn -pl scrapper -am checkstyle:check

